c_compiler:                # [win]
  - clang                  # [win]
cxx_compiler:              # [win]
  - clangxx                # [win]
fortran_compiler_version:  # [win]
  - 20                     # [win]
