{% set version = "2.3.3" %}
{% set commit = "c2e0b548" %}
#{% set sha256 = "87c090b7415cd2126608019cad7a3e008c25171c7c8189adad399b6a86f8d383" %}
{% set sha256 = "a4f59921b388c041acb433beb4fb96b5399179c68bd1fd1d97905f4f3f2cd64d" %}

package:
  name: gdma-split
  version: {{ version }}

source:
  url: https://github.com/psi4/gdma/archive/wipflang.tar.gz  # equivalent to upstream plus patches
  #url: https://github.com/psi4/gdma/archive/v2.3.3.tar.gz  # equivalent to upstream plus patches
  #url: https://gitlab.com/anthonyjs/gdma/-/archive/{{ commit }}.tar.bz2
  #patches:
  #  - 0001-add-CMake-library-pymod-IO-git-avoidance.patch
  #  - 0002-real128-to-real64.patch
  ## 0002-real128-to-real64.patch only win evenually TODO
  ##patches:  # also equivalent to upstream plus single big patch, but c-b predicts patch levels wrong
  ##  - 0001-fix-use-input-bug-build-outside-git-generalize-pytho.patch
  ##  - 0002-add-IO-management-form-library-as-well-as-executable.patch
  ##  - 0003-add-CMake-buildsystem-for-L-M-W-platforms.patch
  ##  - 0004-add-exports-to-Python-module.patch
  ##  - 0005-avoid-git-for-c-f.patch
  sha256: {{ sha256 }}

build:
  number: 6
  binary_relocation: true

outputs:
  - name: gdma
    script: build-cxx.sh                                                         # [unix]
    script: bld-cxx.bat                                                          # [win]
    build:
      run_exports:
        - {{ pin_subpackage('gdma', max_pin='x.x') }}
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("fortran") }}
        - cmake
        - ninja
        - python 3.10                                                                      # only for generating a source file, so suppress all but one Py version. update as necessary.
      run:
    test:
      source_files:
        - examples/H2O/data
        - examples/H2O/H2O.fchk
      commands:
        - ls -l $PREFIX/lib                                                      # [unix]
        - ls -l $PREFIX/share/cmake/gdma                                         # [unix]
        - dir %PREFIX%\\Library\\lib                                             # [win]
        - dir %PREFIX%\\Library\\share\\cmake\\gdma                              # [win]
        - dir %PREFIX%\\Library\\bin                                             # [win]
        # Verify library
        - test -f $PREFIX/lib/libgdma$SHLIB_EXT                                  # [unix]
        - test ! -f $PREFIX/lib/libgdma.a                                        # [unix]
        # Verify accessories
        - test -f $PREFIX/bin/gdma                                               # [unix]
        - test -f $PREFIX/include/GDMA/GDMA_MANGLE.h                             # [unix]
        - test -f $PREFIX/share/cmake/gdma/gdmaConfig.cmake                      # [unix]
        - test -f $PREFIX/share/cmake/gdma/gdmaTargets-lib.cmake                 # [unix]
        # Inspect linkage
        - ldd -v $PREFIX/lib/libgdma$SHLIB_EXT                                   # [linux and build_platform == target_platform]
        - otool -L $PREFIX/lib/libgdma$SHLIB_EXT                                 # [osx]
        # Actually test
        - echo aaa
        - cd examples/H2O/
        #- cd examples/H2O/ && gdma < data                                        # [unix]
        - gdma < data                                        # [unix]
        - echo aaa2
        #- cd examples/H2O/ && gdma.exe < data                                    # [win]
        - dir .  # [win]
        - echo aaa3
        - gdma.exe
        - echo aaa4
        - gdma.exe < data                                    # [win]
        - echo aaa5

  - name: pygdma
    script: build-py.sh                                                          # [unix]
    script: bld-py.bat                                                           # [win]
    build:
      skip: true                                                                 # [win or ((aarch64 or ppc64le) and python_impl == 'pypy')]
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python                                                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}                                     # [build_platform != target_platform]
        - pybind11                                                               # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('gdma', exact=True) }}
        - python
        - pybind11
        - pybind11-abi
      run:
        - {{ pin_subpackage('gdma', exact=True) }}
        - python
    test:
      requires:
        - pip                                                                              # provides `pip check`
      source_files:
        - examples/H2O/data
        - examples/H2O/H2O.fchk
      imports:
        - gdma
      commands:
        # Verify module
        - test -f $SP_DIR/gdma*.so                                               # [unix]
        - if not exist %SP_DIR%\\gdma*.pyd exit 1                                # [win]
        # Verify accessories
        - test -f $PREFIX/share/cmake/gdma/gdmaConfig.cmake                      # [unix]
        - test -f $PREFIX/share/cmake/gdma/gdmaTargets-Python.cmake              # [unix]
        - if not exist %PREFIX%\\Library\\share\\cmake\\gdma\\gdmaConfig.cmake exit 1  # [win]
        - if not exist %PREFIX%\\Library\\share\\cmake\\gdma\\gdmaTargets-Python.cmake exit 1  # [win]
        # Inspect linkage
        - ldd -v $SP_DIR/gdma*.so                                                # [linux and build_platform == target_platform]
        - otool -L $SP_DIR/gdma*.so                                              # [osx]
        # Actually test
        - pip check
        - echo aaa
        - python -c "import gdma; print(gdma.__version__)"
        - echo vvv
        - cd examples/H2O/ && python -c "import gdma; gdma.run_gdma('stdout', 'data')"
        - echo zzz

about:
  home: https://www-stone.ch.cam.ac.uk/pub/gdma/
  dev_url: https://gitlab.com/anthonyjs/gdma
  doc_url: https://gitlab.com/anthonyjs/gdma/-/blob/master/doc/manual.pdf
  doc_source_url: https://gitlab.com/anthonyjs/gdma/-/tree/master/doc
  license: GPL-3.0-only
  license_url: https://opensource.org/license/gpl-3-0/
  license_file: LICENCE
  license_family: GPL
  summary: "A. J. Stone's Distributed Multipole Analysis for Gaussian wavefunctions"

extra:
  feedstock-name: gdma
  recipe-maintainers:
    - loriab
    - davpoolechem
